version: "3"
services:
  go-rest-service-postgres:
    image: postgres:12.10
    network_mode: bridge
    container_name: go-rest-service-postgres
    volumes:
      - go-rest-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  go-rest-data:
